### PR TITLE
Small typo fixes and reStructuredText formatting

### PR DESCRIPTION
**Pull request by vincent-legoll**

### CODE REVIEW

**Comment by vincent-legoll** [comment]
I did not want to do it myself, but you may want to update copyright dates, there are some still in 2016...

**Comment by seveas** [comment]
Thanks, cherrypicked most of this in fc83cf9 (I skipped the gitignore change and a grammatical change I disagree with)

**Comment by vincent-legoll** [comment]
Thanks for the merged parts.

I'm not a native-english speaker, so may be wrong, but I still think this is not good :
`or remotely using the iLO's built-in webserver.`

I choose one of the two alternatives I think are better english :
- `or remotely using iLO's built-in webserver.`
- `or remotely using the iLO built-in webserver.`

But I won't be fighting over this. ;-)

**Comment by seveas** [comment]
The original is better: it's the webserver of the iLO, so the iLO's built-in webserver.

**Pull request closed without merging**
