### PR TITLE
attempt to fix broken entry with text in quotation marks

### LINKED ISSUE #188: quotation marks in XML/RIBCL
unfortunately the output of an ILO4 had quotation marks in the description tag:
DESCRIPTION="Embedded Flash/SD-CARD: Failed to initialize the "blackbox:a" storage device driver
."

this should be escaped to $quot

### PR DESCRIPTION
**Pull request by conrad784**
closes #188 
offending line:
DESCRIPTION="Embedded Flash/SD-CARD: Failed to initialize the "blackbox:a" storage device driver
."

this solution might not be very optimized...

### CODE REVIEW

**Comment by seveas** [comment]
Thanks! Have you reported this to HP as well? They really should fix this in the ilo firmware.

As the collection of these hacks to deal with unescaped quotation marks is getting ridiculous, I'm going to have a think about a better solution before merging this.

**Comment by conrad784** [comment]
> Have you reported this to HP as well? They really should fix this in the ilo firmware.
It isn't valid XML, but maybe valid RIBCL ;)
I don't know where I should report this, without failing with the first-level support.

**Comment by conrad784** [comment]
I adapted my latest patch to your other strategies with re.sub and calling the `fix` function.
One could also call ```data = re.sub(r''' ".+" ''', lambda match: match.group().replace('"', '&quot;'), data)```

**Comment by seveas** [comment]
Could you try with 2712ee4 instead? It has a more generic fix for unescaped quotation marks.

**Comment by conrad784** [comment]
Works for me! Your fix should handle all problem with the falsely used quotation marks and is better understandable than the regex hacks.
Tested also for multiple wrong entries and also if it is the last entry. Are there any other edge cases?

I did some timeit tests and for a `81556` list and 1000 iterations it takes now 7.2s instead of 4.5s.
But this is bearable as it only takes one call and the request from the iLO is so much slower...

**Comment by seveas** [comment]
Yeah, I'm not too worried about performance in this method. It's only called for malformed XML, and the ilo itself is a lot slower (as you also mention). Closing this PR and I'll merge the other one instead.

**Pull request closed without merging**
